apiVersion: v1
kind: Service
metadata:
  name: nexus-app-service
  namespace: tooling 
spec:
  selector:
    app: nexus-app
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
  type: ClusterIP
